spring:
  application:
    name: eureka

server:
  port: 2001
eureka:
  server:
    enable-self-preservation: false #\u5173\u95ED\u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false   #\u4E0D\u5411\u81EA\u5DF1\u6CE8\u518C
    fetch-registry: false         #\u4E0D\u5411\u81EA\u5DF1\u62C9\u53D6
