eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true   #\u4E0D\u5411\u81EA\u5DF1\u6CE8\u518C
    fetch-registry: true         #\u4E0D\u5411\u81EA\u5DF1\u62C9\u53D6
    service-url:
      defaultZone:  http://eureka1:2001/eureka